apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "image_builder_application.fullname" . }}-database-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "image_builder_application.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
data: 
  init.sql: |
    CREATE DATABASE IF NOT EXISTS image_builder;
    USE image_builder;
  my.cnf: |
    [mysqld]
    bind-address = 0.0.0.0
    user=root
    init_connect='SET collation_connection = utf8mb4_unicode_ci'
    init_connect='SET NAMES utf8mb4'
    character-set-server=utf8mb4
    collation-server=utf8mb4_unicode_ci
    skip-character-set-client-handshake