apiVersion: v1
kind: Secret
metadata:
  name: {{ include "image_builder_application.fullname" . }}-secret
  {{- if .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
  {{- end }}
  labels:
    {{- range $key, $value := .Values.secretLabels }}
    {{ $key }}: {{ $value }}
    {{- end }}
  annotations:
    {{- with .Values.secrets.secretAnnotations }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
stringData:
  config.ini: |
    [github]
    local_work_dir = code_repo
    access_token = {{ .Values.github.token }}
    
    [docker_hub]
    registry_user_name = forme628
    
    [mysql]
    host = localhost
    port = 3306
    user = {{ .Values.dbInfo.user }}
    password = {{ .Values.dbInfo.passwd }}
    db_name = image_builder
    
    [log]
    local_log_dir = log
    
    [server]
    host = 0.0.0.0
    port = 9001
  dbUser: {{ .Values.dbInfo.user | quote }}
  dbPasswd: {{ .Values.dbInfo.passwd | quote }}
